project:
  type: website
  output-dir: docs

website:
  # title: "OBAMA-NEXT GitHub Organisation"
  navbar:
    logo: "/img/logo-4-300x226.jpg"
    logo-alt: "OBAMA-NEXT logo"
    left: 
      - href: index.qmd
        text: Home
      - href: products.qmd
        text: Products
      - href: blueprint.qmd
        text: Blueprint
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 4


render:
    - section1.qmd
    - section2.qmd
csl: frontiers-in-marine-science.csl